In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
train_data = pd.read_csv('Downloads/fraudTrain.csv')
train_data.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [3]:
test_data = pd.read_csv('Downloads/fraudTest.csv')
test_data.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [4]:
train_data_ = train_data
test_data_ = test_data

In [5]:
pd.set_option('display.max_columns',None)
train_data_.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [6]:
test_data_.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,NY,11710,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,Titusville,FL,32780,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,Falmouth,MI,49632,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [7]:
train_data_.shape

(1296675, 23)

In [8]:
test_data_.shape

(555719, 23)

In [9]:
train_data_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [10]:
column_names=train_data_.columns
categorical_columns=[var for var in column_names if train_data_[var].dtype=='object']
print("The columns with categorical data are : {}".format(categorical_columns))

The columns with categorical data are : ['trans_date_trans_time', 'merchant', 'category', 'first', 'last', 'gender', 'street', 'city', 'state', 'job', 'dob', 'trans_num']

In [11]:
train_data_[categorical_columns].head()

,trans_date_trans_time,merchant,category,first,last,gender,street,city,state,job,dob,trans_num
0,2019-01-01 00:00:18,"fraud_Rippin, Kub and Mann",misc_net,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9
1,2019-01-01 00:00:44,"fraud_Heller, Gutmann and Zieme",grocery_pos,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99
2,2019-01-01 00:00:51,fraud_Lind-Buckridge,entertainment,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95
3,2019-01-01 00:01:16,"fraud_Kutch, Hermiston and Farrell",gas_transport,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81
4,2019-01-01 00:03:06,fraud_Keeling-Crist,misc_pos,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46

In [12]:
train_data_['trans_num'].unique()

array(['0b242abb623afc578575680df30655b9',
       '1f76529f8574734946361c461b024d99',
       'a1a22d70485983eac12b5b88dad1cf95', ...,
       '483f52fe67fabef353d552c1e662974c',
       'd667cdcbadaaed3da3f4020e83591c83',
       '8f7c8e4ab7f25875d753b422917c98c9'], dtype=object)

In [13]:
train_data_=train_data_.drop('trans_num',axis=1)

In [14]:
train_data_['dob'].unique()

array(['1988-03-09', '1978-06-21', '1962-01-19', '1967-01-12',
       '1986-03-28', '1961-06-19', '1993-08-16', '1947-08-21',
       '1941-03-07', '1974-03-28', '1990-07-13', '1966-02-14',
       '1989-02-28', '1945-12-21', '1967-08-30', '1965-06-30',
       '1952-07-06', '1938-03-15', '1946-02-02', '1980-12-21',
       '1980-11-22', '1961-02-14', '1974-07-19', '1965-07-26',
       '1946-01-02', '1962-08-13', '1971-11-05', '1967-08-02',
       '1966-12-03', '1945-03-15', '1961-05-19', '1964-12-30',
       '1964-04-22', '1977-02-22', '1970-07-20', '1984-06-04',
       '1970-10-21', '1984-12-24', '1998-10-01', '1988-04-27',
       '1987-07-18', '1971-10-14', '1987-04-23', '1942-01-06',
       '1971-01-28', '1972-07-25', '1984-09-01', '1960-01-06',
       '1986-11-06', '1954-01-05', '1970-09-27', '1994-02-09',
       '1942-11-24', '1994-11-05', '1993-10-25', '1976-10-18',
       '1981-02-15', '1974-03-13', '1926-07-12', '1966-12-21',
       '1936-03-28', '1997-08-22', '1972-05-04', '1955-06-12',
       '1990-08-13', '1967-02-04', '1974-06-21', '1962-11-11',
       '1983-07-25', '1979-01-02', '2000-06-13', '1957-03-28',
       '1955-01-05', '1976-02-26', '1982-01-07', '1935-09-08',
       '1975-04-30', '1977-04-28', '1954-05-25', '1946-04-03',
       '1975-07-31', '1998-03-19', '1974-12-23', '1995-07-12',
       '1989-11-24', '1983-08-25', '1984-06-03', '1935-08-15',
       '1995-04-19', '1976-09-08', '1946-08-24', '1971-08-20',
       '1957-03-06', '1970-09-11', '1977-01-04', '1986-06-11',
       '1989-04-08', '1986-06-20', '1980-12-16', '1978-07-08',
       '1957-12-29', '1972-06-14', '1935-04-15', '1927-09-09',
       '1928-10-01', '1950-08-19', '1958-06-26', '1926-09-14',
       '1935-02-10', '1962-04-12', '1951-02-05', '1985-03-21',
       '1990-05-03', '1945-09-20', '1961-01-21', '1972-11-28',
       '1972-07-01', '1958-08-14', '1985-09-02', '2001-07-26',
       '1929-05-06', '1960-06-14', '1954-06-14', '1977-10-19',
       '1971-11-02', '1950-11-27', '1963-05-23', '1948-11-14',
       '1966-11-10', '1990-10-15', '1963-04-22', '1954-12-10',
       '1968-07-01', '1973-04-01', '1988-09-15', '1988-04-15',
       '1959-09-27', '1999-06-06', '1985-01-01', '2003-05-07',
       '1957-01-23', '1927-12-11', '1981-06-22', '1962-06-04',
       '1990-06-25', '1960-01-16', '1954-07-15', '1984-07-03',
       '1971-08-06', '1950-04-05', '1967-05-28', '1952-10-13',
       '1983-10-14', '1969-03-02', '1968-10-06', '1931-01-26',
       '1940-11-11', '1987-11-18', '1965-12-15', '1962-10-16',
       '1981-07-05', '1934-03-19', '1989-07-17', '1992-05-09',
       '1982-05-20', '1929-08-23', '1971-03-26', '1995-05-25',
       '1997-06-04', '1951-12-04', '1967-05-27', '1939-09-19',
       '1986-05-02', '1936-03-27', '1958-06-11', '1953-03-30',
       '1997-03-12', '1963-12-29', '1957-04-17', '1998-10-07',
       '1981-10-24', '1971-04-25', '1970-02-22', '1956-01-09',
       '1968-06-18', '1969-10-30', '1995-10-17', '1978-01-15',
       '1954-07-05', '1926-06-26', '1960-01-20', '1964-01-04',
       '1945-08-19', '1934-10-06', '1974-10-27', '1951-11-08',
       '1963-06-22', '1963-04-04', '1968-02-10', '1993-07-05',
       '1978-03-06', '1980-05-18', '1970-11-12', '1977-06-07',
       '1982-02-10', '1926-08-27', '1969-09-21', '1970-03-13',
       '1974-03-10', '1939-11-09', '1986-12-13', '1958-04-06',
       '1973-07-28', '1953-01-20', '1977-08-16', '2004-05-08',
       '1992-01-20', '2005-01-29', '1974-02-15', '1972-05-23',
       '1945-11-04', '1958-09-20', '1972-10-18', '1937-03-17',
       '1961-10-24', '1983-07-24', '1955-05-06', '1951-01-15',
       '1954-06-30', '1956-01-24', '1958-09-02', '1948-06-30',
       '1969-07-24', '1954-08-22', '1961-09-10', '1980-08-18',
       '1964-08-23', '1978-08-27', '1969-08-04', '1988-03-25',
       '1979-06-24', '1985-04-15', '1973-05-07', '1975-07-07',
       '1978-03-04', '1959-07-30', '1952-04-02', '1928-07-15',
       '1980-09-15', '1956-09-15', '1986-12-17', '1969-11-22',
       '1954-07-14', '1952-09-27', '1973-02-14', '1960-02-01',
       '1942-04-03', '1933-03-15', '1964-02-13', '1963-02-09',
       '1974-11-02', '1929-05-30', '1964-11-17', '1934-06-23',
       '1960-04-03', '1987-05-19', '1955-07-25', '1976-09-17',
       '1996-04-10', '1944-07-26', '1988-02-15', '1969-02-22',
       '1993-04-08', '1970-06-09', '1991-03-13', '1964-08-08',
       '1953-12-08', '1975-12-28', '1959-05-10', '1972-10-04',
       '1997-07-05', '1990-11-23', '1962-09-27', '1975-07-13',
       '1967-09-16', '1971-02-11', '1982-07-30', '1973-01-21',
       '1993-10-12', '1964-02-15', '1969-11-01', '1973-05-16',
       '1990-11-07', '1956-05-30', '1950-05-27', '1980-08-17',
       '1974-10-15', '1961-01-31', '1973-06-09', '1969-12-22',
       '1962-05-04', '1984-07-05', '1927-10-24', '1967-01-24',
       '1976-03-26', '1983-06-23', '1990-01-24', '1965-04-13',
       '1957-04-05', '1966-01-04', '1979-04-12', '1983-10-12',
       '2001-06-22', '1991-10-13', '1993-11-17', '1974-11-20',
       '1963-08-04', '1956-09-01', '1981-05-06', '1995-03-13',
       '1976-09-29', '1958-01-01', '1979-12-11', '1976-05-16',
       '1984-08-01', '1953-05-23', '1991-04-13', '1949-10-04',
       '1958-10-29', '1955-11-07', '1973-10-19', '1968-06-24',
       '1951-09-03', '1955-11-10', '1964-04-06', '1962-02-14',
       '1991-10-04', '1976-06-15', '1962-04-05', '1999-09-11',
       '1989-05-14', '1968-02-09', '1950-11-20', '1992-06-19',
       '1936-11-05', '1966-09-16', '1954-01-06', '1987-09-26',
       '1953-07-30', '1942-05-04', '1968-07-24', '1982-08-01',
       '1963-06-13', '1993-05-14', '1986-03-14', '1969-09-15',
       '1987-05-05', '1974-12-05', '1975-06-29', '1941-04-23',
       '1948-05-01', '1961-09-03', '1986-04-28', '1943-05-28',
       '1953-12-25', '1954-01-29', '1992-07-23', '1976-01-02',
       '1941-10-16', '1972-04-18', '1993-11-02', '1991-06-05',
       '1984-11-06', '1959-10-07', '1951-06-13', '1975-12-20',
       '1960-01-13', '1991-01-28', '1970-03-14', '1961-04-25',
       '1958-07-28', '1988-09-02', '1998-07-29', '1971-12-10',
       '1973-07-13', '1999-10-25', '1958-10-26', '1967-06-20',
       '1966-06-07', '1986-05-01', '1984-03-03', '1976-10-09',
       '1955-01-20', '1956-10-08', '1965-04-27', '1999-11-30',
       '1966-05-22', '1949-10-13', '1957-01-15', '1942-04-17',
       '1941-11-16', '1995-07-08', '1983-02-08', '1961-04-22',
       '1969-05-16', '1968-05-13', '1970-10-09', '1978-08-08',
       '1968-11-22', '1960-11-19', '1976-06-30', '1952-03-08',
       '1972-08-09', '1991-03-29', '1990-10-28', '1997-11-18',
       '1952-01-29', '1992-11-27', '1987-09-19', '1985-12-27',
       '1970-01-08', '1983-08-24', '1956-05-02', '1989-10-06',
       '1965-09-15', '1979-07-03', '1986-01-30', '1968-05-16',
       '1994-03-13', '1957-08-08', '1987-04-24', '1935-01-29',
       '1941-03-30', '1978-01-22', '1982-07-02', '1959-05-28',
       '1939-03-09', '1986-11-12', '1959-08-05', '1962-03-20',
       '1985-08-29', '1980-03-18', '1990-11-09', '1974-05-18',
       '1972-07-18', '1940-09-13', '1991-08-19', '1994-11-24',
       '1974-12-24', '1981-08-29', '1988-09-19', '1973-02-07',
       '1967-06-19', '1977-08-12', '1955-07-06', '1978-12-18',
       '1965-11-11', '1946-08-30', '1949-03-20', '1986-07-23',
       '1979-09-03', '1958-02-17', '1977-06-14', '1950-03-25',
       '1957-11-12', '1994-04-22', '1982-02-08', '1974-09-14',
       '1966-01-21', '1964-06-22', '1927-05-25', '1984-03-06',
       '1973-05-27', '1938-09-08', '1987-02-22', '1971-08-05',
       '1961-11-24', '1935-06-29', '1978-05-23', '1985-06-18',
       '1976-11-21', '1957-08-30', '1953-04-19', '1999-12-27',
       '1971-07-02', '1977-03-23', '1980-01-09', '1974-01-03',
       '1992-10-07', '1988-10-26', '1980-07-12', '1930-08-13',
       '1967-04-09', '1988-08-04', '1974-12-28', '1987-04-29',
       '1956-06-22', '1983-06-14', '1985-05-25', '1986-03-31',
       '1973-12-26', '1977-12-16', '1972-01-20', '1936-05-01',
       '1976-09-12', '1966-02-21', '1991-05-01', '1989-03-09',
       '1948-05-31', '1965-04-07', '1982-05-28', '1932-03-10',
       '1946-11-01', '1993-02-26', '1943-06-30', '1990-06-08',
       '1931-03-07', '2000-06-09', '1975-04-16', '1986-01-18',
       '1981-08-10', '1987-01-27', '1989-10-28', '1978-09-30',
       '1983-09-02', '1989-12-17', '1993-09-11', '1985-03-19',
       '1979-04-30', '1962-02-13', '1946-08-11', '1985-12-03',
       '1990-10-19', '1978-10-26', '1994-10-07', '1972-09-22',
       '1973-11-14', '1960-03-01', '1995-12-28', '1937-02-01',
       '1956-03-02', '1991-02-03', '1974-04-16', '1939-11-04',
       '1997-01-02', '1979-01-21', '1966-02-13', '1983-06-12',
       '1984-07-20', '1983-07-10', '2004-12-30', '1963-05-19',
       '1993-10-07', '1983-06-13', '1999-03-05', '1993-10-05',
       '1970-04-17', '1987-10-28', '1991-02-04', '1980-09-18',
       '1986-02-17', '1988-07-28', '1974-05-30', '1984-02-14',
       '1932-11-19', '1975-06-02', '1988-09-06', '1958-09-10',
       '1978-10-05', '1989-02-08', '1949-11-17', '1994-11-12',
       '1980-07-30', '2001-07-05', '1997-12-27', '1963-06-30',
       '1940-08-23', '1933-04-02', '1949-11-16', '2003-09-14',
       '1985-06-20', '1987-05-23', '1995-04-22', '1978-10-01',
       '1966-08-08', '1986-11-24', '1982-02-11', '1992-07-24',
       '1999-06-19', '1998-05-20', '1955-06-26', '1990-01-17',
       '1987-07-25', '1961-12-14', '1990-12-18', '1959-06-28',
       '1982-02-05', '1970-01-18', '1972-06-12', '1987-06-13',
       '1992-10-03', '1973-05-04', '1988-01-04', '1943-12-15',
       '1945-05-05', '1997-09-22', '1955-02-01', '1963-12-28',
       '1978-12-25', '1960-08-05', '1965-03-25', '1998-02-03',
       '1984-02-07', '1984-05-19', '1969-09-11', '1984-02-29',
       '1994-07-27', '1964-02-18', '1991-10-22', '1995-08-16',
       '1940-09-17', '1986-05-07', '1939-04-14', '1984-05-04',
       '1941-07-31', '1995-11-29', '1960-03-12', '1955-04-03',
       '2000-08-28', '1972-02-15', '1944-11-11', '2004-03-18',
       '1986-12-31', '1991-04-11', '1995-09-11', '1986-04-15',
       '1982-01-16', '1986-08-17', '1997-07-01', '1990-05-22',
       '1960-12-13', '1977-06-12', '1969-01-14', '1985-08-31',
       '1963-06-04', '1952-05-07', '1981-11-29', '1952-12-07',
       '1959-06-06', '1987-09-08', '1993-11-24', '1993-05-10',
       '1995-01-15', '1936-07-22', '1967-05-05', '1996-11-12',
       '1957-04-25', '1977-07-17', '1973-04-06', '1968-03-19',
       '1989-07-08', '1955-01-13', '1998-03-18', '1994-03-01',
       '1994-02-16', '1990-02-25', '1992-12-29', '1988-11-01',
       '1976-04-11', '1968-03-24', '1990-04-25', '1985-08-21',
       '1978-11-30', '1930-10-21', '1992-11-20', '1970-11-09',
       '1949-04-24', '1987-02-14', '1993-03-23', '1972-01-03',
       '1965-04-01', '1973-10-14', '1972-09-12', '1991-01-01',
       '1987-02-13', '1995-12-04', '1976-01-10', '1997-12-26',
       '1961-05-13', '1984-12-16', '1973-09-22', '1988-03-21',
       '1963-07-14', '1948-11-30', '1967-08-24', '1962-04-30',
       '1968-05-29', '1966-09-19', '1980-03-24', '1947-07-15',
       '1972-10-05', '1976-12-10', '1962-05-13', '1962-06-27',
       '1962-11-18', '1956-05-15', '1972-03-05', '1956-12-13',
       '1979-12-27', '1982-12-27', '1985-05-13', '1953-04-13',
       '1985-12-08', '1985-07-08', '1975-10-11', '1991-04-22',
       '1997-10-23', '1970-06-27', '1999-05-31', '1961-12-05',
       '1971-10-19', '1945-11-26', '1987-10-26', '1968-01-28',
       '1962-03-04', '1971-09-01', '1943-12-17', '1976-12-14',
       '1979-10-22', '1968-09-19', '1939-06-01', '1975-11-30',
       '1985-04-03', '1995-10-10', '1999-09-01', '1991-07-06',
       '1985-03-31', '1972-12-31', '1929-03-19', '1989-12-10',
       '1994-05-31', '1972-01-05', '1987-08-16', '1944-05-14',
       '1949-06-09', '2000-02-20', '1985-04-04', '1972-03-28',
       '1957-12-26', '1932-09-17', '1979-08-14', '1967-10-18',
       '1969-05-01', '1967-03-17', '1982-04-19', '1950-09-15',
       '1976-04-12', '1991-01-31', '1981-01-06', '1975-01-26',
       '1993-05-27', '2004-06-19', '1967-10-04', '1993-09-29',
       '1970-11-20', '1950-04-17', '1953-03-19', '1967-03-30',
       '1993-04-29', '1948-04-11', '1929-04-22', '1997-11-23',
       '1976-01-15', '1960-04-08', '1930-02-28', '1945-12-07',
       '1960-10-28', '1979-01-26', '1985-09-01', '1961-12-18',
       '2000-08-16', '1969-11-20', '1971-12-12', '1966-05-10',
       '1949-08-14', '1979-01-08', '1946-03-21', '1965-02-03',
       '1983-03-20', '1954-07-21', '1987-10-27', '1981-03-29',
       '1928-04-02', '1981-03-04', '1952-12-05', '1997-08-04',
       '1947-10-27', '1953-10-18', '1967-03-12', '1948-09-07',
       '1966-06-24', '1956-09-14', '1965-11-06', '1972-09-13',
       '1983-11-10', '1992-10-08', '1994-07-09', '1984-09-13',
       '1966-06-19', '1967-09-30', '1990-06-21', '1994-12-08',
       '1990-09-12', '1966-05-29', '1995-08-30', '1982-06-27',
       '1978-10-04', '1959-03-31', '1975-09-11', '1977-05-18',
       '1991-08-21', '1999-06-28', '1975-12-24', '1931-09-12',
       '1947-08-14', '1962-03-19', '1962-12-06', '1961-09-28',
       '1987-02-26', '1955-12-04', '1934-02-09', '1986-04-03',
       '1964-03-15', '1969-03-20', '1948-03-22', '1966-12-15',
       '1933-03-01', '1987-09-22', '1981-01-26', '1959-01-15',
       '2001-12-19', '1982-02-19', '1928-06-26', '1964-03-16',
       '1964-06-25', '1965-09-27', '1971-01-19', '1976-05-24',
       '1927-08-25', '1973-10-09', '1975-06-25', '1988-04-09',
       '1975-06-01', '1942-04-02', '1981-02-18', '1964-08-18',
       '1967-09-23', '1969-12-12', '1929-04-07', '1940-09-06',
       '1937-02-06', '1990-01-13', '1990-06-13', '1986-10-17',
       '1984-08-31', '1950-12-14', '1969-09-08', '1989-08-16',
       '1956-05-01', '1961-11-07', '1959-06-18', '1997-01-18',
       '1975-10-07', '1924-10-30', '1959-10-19', '1952-05-26',
       '1967-10-28', '1996-01-11', '1983-01-21', '1971-11-26',
       '1959-05-30', '2001-07-10', '1985-01-02', '1972-08-15',
       '1965-11-21', '1963-09-11', '1983-01-08', '1961-07-31',
       '1972-07-29', '1961-09-13', '1957-06-12', '1987-11-30',
       '1967-08-28', '1951-03-31', '1989-10-19', '2000-02-15',
       '1962-03-14', '1997-08-08', '1970-06-25', '1943-07-25',
       '1961-06-16', '1968-10-26', '1996-01-10', '1944-06-17',
       '1966-08-03', '1925-08-29', '1996-04-04', '1937-04-16',
       '1962-11-15', '1940-11-08', '1964-11-18', '1963-02-26',
       '1927-02-03', '1996-04-01', '1999-09-29', '1938-08-07',
       '2001-07-17', '1965-08-18', '2000-03-16', '1940-10-27',
       '1956-03-20', '1963-03-13', '1961-06-18', '1949-02-15',
       '1939-04-13', '1998-12-29', '1961-01-30', '1949-02-25',
       '1963-02-20', '1941-09-30', '1957-12-17', '1948-05-16',
       '1996-07-04', '1940-03-06', '1957-07-27', '1970-03-16',
       '1964-02-21', '1957-04-20', '1946-05-28', '1999-10-26',
       '1949-04-28', '1998-11-12', '1952-11-23', '1966-07-25',
       '1957-04-15', '1934-05-04', '1960-02-21', '1966-06-12',
       '1958-03-18', '1963-03-08', '1968-10-14', '1931-04-21',
       '1946-11-20', '1964-09-17', '1932-08-10', '1997-04-06',
       '1941-07-06', '1936-05-04', '1930-06-26', '1943-08-04',
       '1962-01-24', '1940-07-30', '1970-01-09', '1963-03-14',
       '1954-07-07', '1934-05-24', '1997-04-17', '1949-12-22'],
      dtype=object)

In [15]:
def find_age(date_of_birth):
    year=int(date_of_birth[:4])
    return (2023-year)
train_data_['dob'] = train_data_['dob'].apply(find_age)
train_data_.rename(columns={'dob':'age'},inplace=True)
train_data_['age'].unique()

array([35, 45, 61, 56, 37, 62, 30, 76, 82, 49, 33, 57, 34, 78, 58, 71, 85,
       77, 43, 52, 59, 46, 53, 39, 25, 36, 81, 51, 63, 69, 29, 47, 42, 97,
       87, 26, 68, 40, 44, 23, 66, 41, 88, 48, 28, 96, 95, 73, 65, 72, 38,
       22, 94, 60, 75, 55, 50, 64, 24, 20, 54, 92, 83, 89, 31, 84, 70, 67,
       19, 18, 86, 90, 27, 79, 32, 74, 80, 93, 91, 99, 98], dtype=int64)

In [16]:
train_data_['merchant'].unique()

array(['fraud_Rippin, Kub and Mann', 'fraud_Heller, Gutmann and Zieme',
       'fraud_Lind-Buckridge', 'fraud_Kutch, Hermiston and Farrell',
       'fraud_Keeling-Crist', 'fraud_Stroman, Hudson and Erdman',
       'fraud_Rowe-Vandervort', 'fraud_Corwin-Collins',
       'fraud_Herzog Ltd', 'fraud_Schoen, Kuphal and Nitzsche',
       'fraud_Rutherford-Mertz', 'fraud_Kerluke-Abshire',
       'fraud_Lockman Ltd', 'fraud_Kiehn Inc', 'fraud_Beier-Hyatt',
       'fraud_Schmidt and Sons', 'fraud_Lebsack and Sons',
       'fraud_Mayert Group', 'fraud_Konopelski, Schneider and Hartmann',
       'fraud_Schultz, Simonis and Little', 'fraud_Bauch-Raynor',
       'fraud_Harris Inc', 'fraud_Kling-Grant', 'fraud_Pacocha-Bauch',
       'fraud_Lesch Ltd', 'fraud_Kunde-Sanford', "fraud_Deckow-O'Conner",
       'fraud_Bruen-Yost', 'fraud_Kunze Inc',
       'fraud_Nitzsche, Kessler and Wolff',
       'fraud_Kihn, Abernathy and Douglas', 'fraud_Torphy-Goyette',
       'fraud_Balistreri-Nader', 'fraud_Bahringer, Schoen and Corkery',
       'fraud_Hudson-Ratke', 'fraud_Heidenreich PLC',
       'fraud_Halvorson Group', 'fraud_Harber Inc',
       'fraud_Mosciski, Gislason and Mertz',
       'fraud_Christiansen, Goyette and Schamberger', 'fraud_Howe Ltd',
       'fraud_Ledner-Pfannerstill', 'fraud_Koepp-Witting',
       'fraud_Doyle Ltd', 'fraud_Schaefer, Maggio and Daugherty',
       'fraud_Stracke-Lemke', 'fraud_Mosciski, Ziemann and Farrell',
       'fraud_Cartwright-Harris', "fraud_Pacocha-O'Reilly",
       'fraud_Pfeffer LLC', 'fraud_Huels-Hahn', 'fraud_Volkman PLC',
       'fraud_Kiehn-Emmerich', 'fraud_Kemmer-Buckridge',
       'fraud_Cummerata-Jones', 'fraud_Goldner, Kovacek and Abbott',
       'fraud_Spinka-Welch', 'fraud_Huel-Langworth',
       'fraud_Macejkovic-Lesch', 'fraud_Morar Inc',
       'fraud_Eichmann, Bogan and Rodriguez',
       'fraud_Huel, Hammes and Witting', 'fraud_Ferry, Lynch and Kautzer',
       'fraud_Heathcote LLC', 'fraud_Little, Gutmann and Lynch',
       'fraud_Jaskolski-Dibbert', 'fraud_Hackett-Lueilwitz',
       'fraud_Cummings LLC', 'fraud_Swaniawski, Lowe and Robel',
       'fraud_Osinski, Ledner and Leuschke',
       'fraud_Reichert, Huels and Hoppe', 'fraud_Ankunding LLC',
       'fraud_Pfeffer and Sons', 'fraud_Greenholt, Jacobi and Gleason',
       'fraud_Connelly, Reichert and Fritsch', 'fraud_Torp-Labadie',
       'fraud_Wolf Inc', 'fraud_VonRueden Group', 'fraud_Vandervort-Funk',
       'fraud_Bernhard Inc', 'fraud_Morissette, Weber and Wiegand',
       'fraud_Brekke and Sons', 'fraud_Mraz-Herzog',
       'fraud_Padberg-Welch', 'fraud_Kutch-Hegmann',
       'fraud_Corwin-Gorczany', 'fraud_Huels-Nolan', 'fraud_DuBuque LLC',
       'fraud_Schmeler Inc', 'fraud_Schaefer, McGlynn and Bosco',
       'fraud_Williamson LLC', 'fraud_Pouros-Conroy',
       'fraud_Erdman-Kertzmann', 'fraud_Kuhn LLC',
       'fraud_Fisher-Schowalter', 'fraud_Medhurst PLC',
       'fraud_Kerluke Inc', 'fraud_Stark-Batz',
       'fraud_Gottlieb, Considine and Schultz',
       'fraud_Adams, Kovacek and Kuhlman', 'fraud_Grimes LLC',
       'fraud_Rodriguez Group', 'fraud_Wuckert-Walter',
       'fraud_Weber and Sons', 'fraud_Herman, Treutel and Dickens',
       'fraud_Rau and Sons', 'fraud_Koss and Sons',
       'fraud_Smitham-Schiller', 'fraud_Hills-Olson', 'fraud_Durgan-Auer',
       'fraud_McDermott-Rice', 'fraud_Raynor, Reinger and Hagenes',
       'fraud_Powlowski-Weimann', 'fraud_Langosh, Wintheiser and Hyatt',
       'fraud_Baumbach, Hodkiewicz and Walsh', 'fraud_Rempel Inc',
       'fraud_Bins-Rice', 'fraud_Emard Inc', 'fraud_Kutch and Sons',
       'fraud_Fisher Inc', 'fraud_Olson, Becker and Koch',
       "fraud_Friesen-D'Amore", 'fraud_Reilly, Heaney and Cole',
       'fraud_Boyer PLC', 'fraud_Luettgen PLC', 'fraud_Cassin-Harvey',
       'fraud_Funk Group', 'fraud_Goodwin-Nitzsche',
       'fraud_Parisian, Schiller and Altenwerth', 'fraud_Metz-Boehm',
       'fraud_Monahan, Bogisich and Ledner', 'fraud_Koelpin and Sons',
       'fraud_Kuhic LLC', 'fraud_Koepp-Parker',
       'fraud_Stehr, Jewess and Schimmel',
       'fraud_Quitzon, Green and Bashirian',
       'fraud_Nicolas, Hills and McGlynn', 'fraud_Leannon-Ward',
       'fraud_Friesen-Stamm', 'fraud_Botsford Ltd', 'fraud_Bradtke PLC',
       'fraud_Zieme, Bode and Dooley', 'fraud_Hills-Witting',
       'fraud_Brown-Greenholt', 'fraud_Bernhard, Grant and Langworth',
       'fraud_Wiza, Schaden and Stark', 'fraud_Buckridge PLC',
       'fraud_Kilback LLC', 'fraud_Spinka Inc',
       'fraud_Kerluke, Kertzmann and Wiza',
       'fraud_Ferry, Reichel and DuBuque', 'fraud_Price Inc',
       'fraud_Johnston, Nikolaus and Maggio', 'fraud_Berge LLC',
       'fraud_Conroy-Cruickshank', 'fraud_Abshire PLC',
       'fraud_Gleason-Macejkovic', 'fraud_McGlynn-Jaskolski',
       'fraud_Bartoletti-Wunsch', 'fraud_Cole PLC',
       'fraud_Lehner, Reichert and Mills', 'fraud_McCullough LLC',
       'fraud_Schmitt Ltd', 'fraud_Pouros-Haag',
       'fraud_Strosin-Cruickshank', 'fraud_Weimann, Kuhic and Beahan',
       'fraud_Donnelly PLC', 'fraud_Lockman, West and Runte',
       'fraud_Torp-Lemke', 'fraud_Kris-Weimann',
       'fraud_Rodriguez, Yost and Jenkins', 'fraud_Wiegand-Lowe',
       'fraud_Auer-Mosciski', 'fraud_Okuneva, Schneider and Rau',
       'fraud_Kassulke PLC', 'fraud_Dach-Nader', 'fraud_Cummings Group',
       'fraud_Reichert, Shanahan and Hayes',
       'fraud_Tromp, Kerluke and Glover',
       'fraud_Bins, Balistreri and Beatty', 'fraud_Trantow PLC',
       'fraud_Miller-Hauck', 'fraud_Kuvalis Ltd', 'fraud_Dickinson Ltd',
       'fraud_Stanton, Jakubowski and Baumbach',
       'fraud_Rohan, White and Aufderhar',
       'fraud_Cormier, Stracke and Thiel',
       'fraud_Tillman, Fritsch and Schmitt',
       'fraud_Christiansen-Gusikowski',
       'fraud_Jenkins, Hauck and Friesen', 'fraud_Reichel Inc',
       'fraud_Prohaska-Murray', 'fraud_Parker, Nolan and Trantow',
       'fraud_Volkman Ltd', 'fraud_Streich, Hansen and Veum',
       'fraud_Kutch LLC', 'fraud_Barton Inc', 'fraud_Dooley-Thompson',
       'fraud_Flatley Group', 'fraud_Turcotte-Halvorson',
       'fraud_Lynch Ltd', 'fraud_Romaguera, Cruickshank and Greenholt',
       'fraud_Gutmann Ltd', 'fraud_Sporer Inc',
       'fraud_Runolfsson and Sons', 'fraud_Block Group',
       'fraud_Bahringer-Larson', 'fraud_Rowe, Batz and Goodwin',
       'fraud_Schmitt Inc', 'fraud_Maggio-Fahey',
       'fraud_Haley, Jewess and Bechtelar',
       'fraud_Ruecker, Beer and Collier',
       'fraud_Robel, Cummerata and Prosacco', 'fraud_Jast-McDermott',
       'fraud_Bernier, Volkman and Hoeger', 'fraud_Heaney-Marquardt',
       'fraud_Hudson-Grady', 'fraud_Towne, Walker and Borer',
       'fraud_Terry-Huel', 'fraud_Kihn-Fritsch', 'fraud_Eichmann-Russel',
       'fraud_Miller-Harris', 'fraud_Schumm PLC',
       'fraud_Greenfelder, Bartoletti and Davis',
       'fraud_Kovacek, Dibbert and Ondricka', 'fraud_Hermann-Gaylord',
       'fraud_Bailey-Morar', 'fraud_McDermott-Weimann', 'fraud_Welch Inc',
       'fraud_Auer-West', 'fraud_Boehm, Predovic and Reinger',
       'fraud_Dibbert and Sons', 'fraud_Lind, Huel and McClure',
       'fraud_Casper, Hand and Zulauf', 'fraud_McCullough Group',
       'fraud_Streich, Dietrich and Barton', "fraud_O'Keefe-Hudson",
       'fraud_Pagac LLC', 'fraud_Bernier, Streich and Jewess',
       "fraud_Greenholt, O'Hara and Balistreri", 'fraud_Dickinson-Rempel',
       'fraud_Dare-Marvin', 'fraud_Spencer PLC', 'fraud_Stamm-Rodriguez',
       'fraud_Langworth, Boehm and Gulgowski',
       'fraud_Larkin, Stracke and Greenfelder',
       'fraud_Yost, Block and Koepp',
       'fraud_Douglas, Schneider and Turner', 'fraud_Kuphal-Predovic',
       'fraud_Parisian and Sons', 'fraud_Flatley-Durgan',
       'fraud_Gislason Group', 'fraud_Bednar Group',
       'fraud_Heller-Langosh', 'fraud_Zboncak Ltd', 'fraud_Gerlach Inc',
       'fraud_Wilkinson Ltd', 'fraud_Moen, Reinger and Murphy',
       'fraud_Kerluke, Considine and Macejkovic', 'fraud_Upton PLC',
       'fraud_Bogisich Inc', 'fraud_Marks Inc', 'fraud_Murray-Smitham',
       'fraud_Frami Group', 'fraud_Ortiz Group', 'fraud_Goldner-Lemke',
       'fraud_Hickle Group', 'fraud_Conroy Ltd',
       'fraud_Schumm, Bauch and Ondricka', 'fraud_McGlynn-Heathcote',
       'fraud_Herman Inc', 'fraud_Gutmann-Upton',
       'fraud_Volkman-Predovic',
       'fraud_Wintheiser, Dietrich and Schimmel',
       'fraud_Raynor, Feest and Miller', 'fraud_Bogisich-Homenick',
       'fraud_Jast and Sons', 'fraud_Baumbach, Strosin and Nicolas',
       'fraud_Towne, Greenholt and Koepp', "fraud_Schamberger-O'Keefe",
       'fraud_Nienow PLC', 'fraud_Emmerich-Luettgen', 'fraud_Mante Group',
       'fraud_Baumbach, Feeney and Morar', 'fraud_Thiel PLC',
       'fraud_Mohr Inc', 'fraud_Hagenes, Kohler and Hoppe',
       'fraud_Block-Parisian', 'fraud_Dooley Inc',
       'fraud_Bashirian Group', 'fraud_Cremin, Hamill and Reichel',
       'fraud_Sawayn PLC', 'fraud_Jewess LLC', 'fraud_Roberts-Beahan',
       'fraud_Brown PLC', 'fraud_Tillman, Dickinson and Labadie',
       'fraud_Reichert, Rowe and Mraz', 'fraud_Kilback Group',
       'fraud_Spencer-Runolfsson', 'fraud_Labadie, Treutel and Bode',
       'fraud_Dach-Borer', 'fraud_Johnson, Runolfsdottir and Mayer',
       'fraud_Smitham-Boehm', 'fraud_Moore, Dibbert and Koepp',
       'fraud_Hamill-Daugherty', 'fraud_Watsica, Haag and Considine',
       'fraud_Smith-Stokes', 'fraud_Kuhic, Bins and Pfeffer',
       'fraud_Nader-Heller', 'fraud_Kozey-Boehm', 'fraud_Stiedemann Inc',
       'fraud_Lehner, Mosciski and King', 'fraud_Reynolds-Schinner',
       'fraud_Koss, McLaughlin and Mayer', 'fraud_Terry, Johns and Bins',
       'fraud_Kemmer-Reinger', 'fraud_Larson-Moen', 'fraud_Kuhic Inc',
       'fraud_Kris-Padberg', 'fraud_Schmeler, Bashirian and Price',
       'fraud_Klocko LLC', 'fraud_Schaefer, Fay and Hilll',
       'fraud_Kling Inc', 'fraud_Turner and Sons', 'fraud_Mohr-Bayer',
       'fraud_Wiza LLC', 'fraud_Skiles-Ankunding',
       'fraud_Jaskolski-Vandervort', 'fraud_Kerluke PLC',
       'fraud_Ernser-Lynch', 'fraud_Zboncak, Rowe and Murazik',
       'fraud_Stoltenberg-Beatty', 'fraud_Kuphal-Bartoletti',
       'fraud_Rempel PLC', 'fraud_Denesik and Sons', 'fraud_Goyette Inc',
       'fraud_Dicki Ltd', 'fraud_Stokes, Christiansen and Sipes',
       'fraud_Hermann and Sons', 'fraud_Gibson-Deckow',
       'fraud_Douglas-White', 'fraud_Murray Ltd', 'fraud_McKenzie-Huels',
       'fraud_Runte-Mohr', 'fraud_Roob, Conn and Tremblay',
       'fraud_Boyer-Reichert', 'fraud_Shanahan-Lehner',
       'fraud_Greenholt Ltd', 'fraud_Kulas Group',
       'fraud_Dare, Fritsch and Zboncak', 'fraud_Waters-Cruickshank',
       'fraud_Kunze, Larkin and Mayert', 'fraud_Bednar Inc',
       'fraud_Schimmel-Olson', 'fraud_Lubowitz, Terry and Stracke',
       'fraud_Schoen-Quigley', 'fraud_Kihn-Schuster',
       'fraud_Padberg-Rogahn', 'fraud_Lynch-Mohr', 'fraud_Hilpert-Conroy',
       'fraud_Jacobi Inc', 'fraud_Berge, Kautzer and Harris',
       'fraud_Hammes-Beatty', 'fraud_Gulgowski LLC',
       'fraud_Schuppe, Nolan and Hoeger', 'fraud_Pollich LLC',
       'fraud_Bernier and Sons', 'fraud_Wilkinson PLC',
       'fraud_Kling-Ernser', "fraud_O'Connell, Botsford and Hand",
       'fraud_Little-Gleichner', 'fraud_Champlin and Sons',
       'fraud_Hoppe-Parisian', 'fraud_Schuppe LLC', 'fraud_Emmerich-Rau',
       'fraud_Beier LLC', 'fraud_Champlin-Casper', 'fraud_Gerhold LLC',
       'fraud_Renner Ltd', 'fraud_Gaylord-Powlowski',
       'fraud_Prosacco, Kreiger and Kovacek', 'fraud_Eichmann-Kilback',
       "fraud_O'Hara-Wilderman", 'fraud_Terry Ltd',
       'fraud_Beier and Sons', "fraud_O'Keefe-Wisoky",
       'fraud_Simonis-Prohaska', 'fraud_Breitenberg-Hermiston',
       'fraud_Brown Inc', 'fraud_Fahey Inc',
       'fraud_Boehm, Block and Jakubowski',
       'fraud_Mante, Luettgen and Hackett', 'fraud_Thompson-Gleason',
       'fraud_Turcotte, Batz and Buckridge',
       'fraud_Goyette, Howell and Collier',
       'fraud_Jones, Sawayn and Romaguera', 'fraud_Medhurst Inc',
       'fraud_Bode-Schuster', 'fraud_Connelly-Carter',
       'fraud_Gottlieb-Hansen', 'fraud_Schroeder, Wolff and Hermiston',
       'fraud_Hettinger, McCullough and Fay',
       'fraud_Pouros, Walker and Spencer', 'fraud_Kub PLC',
       'fraud_Watsica LLC', 'fraud_Stiedemann Ltd',
       'fraud_Hauck, Dietrich and Funk', 'fraud_Labadie LLC',
       'fraud_Friesen Inc', 'fraud_Crist, Jakubowski and Littel',
       'fraud_Hodkiewicz, Prohaska and Paucek',
       'fraud_McDermott, Osinski and Morar', 'fraud_Fritsch and Sons',
       'fraud_Swaniawski, Nitzsche and Welch',
       'fraud_Windler, Goodwin and Kovacek',
       'fraud_Yost, Schamberger and Windler',
       'fraud_Metz, Russel and Metz', 'fraud_Erdman-Durgan',
       'fraud_Bahringer, Bergnaum and Quitzon', 'fraud_Veum-Koelpin',
       'fraud_Becker, Harris and Harvey', 'fraud_Monahan-Morar',
       'fraud_Johns Inc', 'fraud_Mosciski Group', 'fraud_Abbott-Steuber',
       'fraud_Schaefer Ltd', 'fraud_Dibbert-Green',
       'fraud_Weimann-Lockman', 'fraud_Kub-Heaney', 'fraud_Zulauf LLC',
       'fraud_Ratke and Sons', 'fraud_Jakubowski Inc', 'fraud_Beer-Jast',
       'fraud_Kautzer and Sons', 'fraud_Feil-Morar',
       'fraud_Johnston-Casper', 'fraud_Medhurst, Labadie and Gottlieb',
       "fraud_Lesch, D'Amore and Brown", 'fraud_Botsford PLC',
       'fraud_Bins-Howell', 'fraud_Kihn Inc',
       'fraud_Hartmann, Rowe and Hermann', 'fraud_Towne LLC',
       'fraud_Lynch-Wisozk', 'fraud_Kutch-Ferry', 'fraud_Goyette-Gerhold',
       'fraud_Bradtke, Torp and Bahringer', 'fraud_Homenick LLC',
       'fraud_Zemlak, Tillman and Cremin',
       'fraud_Schneider, Hayes and Nikolaus',
       'fraud_Schumm, McLaughlin and Carter', 'fraud_Nader-Maggio',
       'fraud_Haley, Batz and Auer', 'fraud_Yost-Rogahn',
       'fraud_Schoen, Nienow and Bauch',
       'fraud_Ledner, Hartmann and Feest', 'fraud_Collier LLC',
       'fraud_Schuppe-Schuppe', 'fraud_Walter, Hettinger and Kessler',
       'fraud_Bechtelar-Rippin', "fraud_Hamill-D'Amore",
       'fraud_Swift PLC', 'fraud_Cronin, Kshlerin and Weber',
       'fraud_Romaguera, Wehner and Tromp',
       'fraud_Feil, Hilpert and Koss', 'fraud_White and Sons',
       'fraud_Mueller, Gerhold and Mueller', 'fraud_Botsford and Sons',
       'fraud_Kirlin and Sons', 'fraud_Bednar PLC',
       'fraud_Runolfsdottir, Mueller and Hand', 'fraud_Kuphal-Toy',
       'fraud_Bahringer-Streich', 'fraud_Wuckert, Wintheiser and Friesen',
       'fraud_Crona and Sons', 'fraud_Prosacco LLC', 'fraud_Schiller Ltd',
       'fraud_Waelchi-Wolf', 'fraud_Torphy-Kertzmann',
       'fraud_McCullough, Hudson and Schuster', 'fraud_Baumbach Ltd',
       'fraud_Schiller, Blanda and Johnson', 'fraud_Cartwright PLC',
       'fraud_Reilly LLC', 'fraud_Cruickshank-Mills',
       'fraud_Altenwerth, Cartwright and Koss',
       'fraud_Effertz, Welch and Schowalter',
       'fraud_Klocko, Runolfsdottir and Breitenberg',
       'fraud_Ruecker-Mayert', 'fraud_Schroeder, Hauck and Treutel',
       'fraud_Lemke-Gutmann', 'fraud_Graham, Hegmann and Hammes',
       'fraud_Reilly and Sons', 'fraud_Stark-Koss', 'fraud_Daugherty LLC',
       'fraud_Denesik, Powlowski and Pouros', 'fraud_Rippin-VonRueden',
       'fraud_Heller PLC', 'fraud_Hills-Boyer', 'fraud_Cormier LLC',
       'fraud_Erdman-Ebert', 'fraud_Bogisich-Weimann',
       'fraud_Gutmann, McLaughlin and Wiza', 'fraud_Little Ltd',
       'fraud_Bode-Rempel', 'fraud_Kutch, Steuber and Gerhold',
       'fraud_Kessler Inc', 'fraud_Deckow-Dare', 'fraud_Rolfson-Kunde',
       'fraud_Marvin-Lind', 'fraud_Barrows PLC', 'fraud_Abbott-Rogahn',
       'fraud_Ziemann-Waters', 'fraud_Reinger, Weissnat and Strosin',
       'fraud_Heathcote, Yost and Kertzmann', 'fraud_Will Ltd',
       'fraud_Kutch-Wilderman', 'fraud_Hermiston, Russel and Price',
       'fraud_Schmidt-Larkin', 'fraud_Lang, Towne and Schuppe',
       'fraud_Weber, Thiel and Hammes',
       'fraud_Hahn, Bahringer and McLaughlin',
       'fraud_Koss, Hansen and Lueilwitz',
       'fraud_Roberts, Ryan and Smith', 'fraud_Hintz, Bauch and Smith',
       'fraud_Monahan, Hermann and Johns',
       'fraud_Bahringer, Osinski and Block',
       'fraud_Douglas, DuBuque and McKenzie', 'fraud_Hackett Group',
       'fraud_Schmeler-Howe', 'fraud_Predovic Inc', 'fraud_Langworth LLC',
       'fraud_Bartoletti and Sons', 'fraud_Bernhard-Lesch',
       'fraud_Satterfield-Lowe', 'fraud_Runte, Green and Emard',
       'fraud_Lowe, Dietrich and Erdman', 'fraud_Jast Ltd',
       'fraud_Welch, Rath and Koepp', 'fraud_Skiles LLC',
       'fraud_Ernser-Feest', 'fraud_Klein Group',
       'fraud_Torp, Muller and Borer', 'fraud_Kuhn Group',
       'fraud_Streich, Rolfson and Wilderman', 'fraud_Bins-Tillman',
       'fraud_Ankunding-Carroll', 'fraud_Hahn, Douglas and Schowalter',
       'fraud_Witting, Beer and Ernser', 'fraud_Morissette LLC',
       'fraud_Berge-Hills', 'fraud_Donnelly LLC', 'fraud_Zboncak LLC',
       'fraud_Turner, Ziemann and Lehner', 'fraud_Padberg-Sauer',
       'fraud_Schulist Ltd', 'fraud_Rau-Grant', 'fraud_Osinski Inc',
       'fraud_Berge-Ullrich', 'fraud_Wuckert-Goldner',
       'fraud_Kertzmann LLC', 'fraud_Daugherty, Pouros and Beahan',
       'fraud_Armstrong, Walter and Gottlieb', 'fraud_Conroy-Emard',
       'fraud_Moore, Williamson and Emmerich', 'fraud_Gleason and Sons',
       'fraud_Roberts, Daniel and Macejkovic', 'fraud_Turner LLC',
       'fraud_Crooks and Sons', 'fraud_Waelchi Inc',
       'fraud_Hoppe, Harris and Bednar', 'fraud_Effertz LLC',
       'fraud_Lubowitz-Walter', 'fraud_Hyatt-Blick', 'fraud_Carroll PLC',
       'fraud_Lemke and Sons', 'fraud_Treutel-King',
       'fraud_Fadel-Hilpert', 'fraud_Altenwerth-Kilback',
       'fraud_Bauch-Blanda', 'fraud_Sporer-Keebler', 'fraud_Hirthe-Beier',
       'fraud_Wisozk and Sons', 'fraud_Streich Ltd', 'fraud_Schoen Ltd',
       'fraud_Windler LLC', 'fraud_Nolan-Williamson',
       'fraud_Roob-Okuneva', 'fraud_Lakin, Ferry and Beatty',
       'fraud_Gottlieb Group', 'fraud_Harris Group', 'fraud_Fritsch LLC',
       'fraud_Corwin-Romaguera', 'fraud_Dietrich-Fadel',
       'fraud_Kling, Howe and Schneider', 'fraud_Kozey-Kuhlman',
       'fraud_Graham and Sons', 'fraud_Jacobi and Sons',
       'fraud_Eichmann, Hayes and Treutel',
       'fraud_Brown, Homenick and Lesch', 'fraud_Erdman-Schaden',
       'fraud_Durgan, Gislason and Spencer', 'fraud_Friesen-Ortiz',
       'fraud_Morissette-Schaefer', 'fraud_Nienow, Ankunding and Collier',
       'fraud_Cole, Hills and Jewess',
       'fraud_Conroy, Balistreri and Gorczany',
       'fraud_Reichel, Bradtke and Blanda',
       "fraud_O'Reilly, Mohr and Purdy", 'fraud_Ullrich Ltd',
       'fraud_Schroeder Group', 'fraud_Boyer-Haley',
       'fraud_Dare, Casper and Bartoletti',
       'fraud_Medhurst, Cartwright and Ebert', 'fraud_Quitzon-Goyette',
       'fraud_Wilkinson LLC', 'fraud_Romaguera and Sons',
       'fraud_Larkin Ltd', 'fraud_Fadel, Mertz and Rippin',
       'fraud_Huel Ltd', 'fraud_Cummerata-Hilpert', 'fraud_Zemlak Group',
       'fraud_Dare-Gibson', 'fraud_Adams-Barrows', 'fraud_Block-Hauck',
       'fraud_Howe PLC', 'fraud_Leffler-Goldner', 'fraud_Tillman LLC',
       'fraud_Pacocha-Weissnat', 'fraud_Morissette PLC',
       'fraud_Jerde-Hermann', 'fraud_Kihn, Brakus and Goyette',
       'fraud_Hills, Hegmann and Schaefer', 'fraud_Friesen Ltd',
       'fraud_Kilback and Sons', 'fraud_Ebert-Daugherty',
       'fraud_Hermiston, Pacocha and Smith', 'fraud_Auer LLC',
       'fraud_Fadel Inc', 'fraud_Daugherty-Thompson',
       'fraud_Romaguera Ltd', 'fraud_Parker-Kunde', 'fraud_Barton LLC',
       'fraud_Kassulke Inc', 'fraud_McLaughlin, Armstrong and Koepp',
       'fraud_Abernathy and Sons', 'fraud_Bahringer Group',
       'fraud_Connelly PLC', 'fraud_Willms, Kris and Bergnaum',
       'fraud_Thiel Ltd', 'fraud_Kris-Kertzmann',
       "fraud_O'Connell-Ullrich", 'fraud_Kozey-McDermott',

In [17]:
train_data_['category'].unique()

array(['misc_net', 'grocery_pos', 'entertainment', 'gas_transport',
       'misc_pos', 'grocery_net', 'shopping_net', 'shopping_pos',
       'food_dining', 'personal_care', 'health_fitness', 'travel',
       'kids_pets', 'home'], dtype=object)

In [18]:
train_data_['name']=train_data_['first']+' '+train_data_['last'].astype(str)
train_data_['name'].unique()
train_data_=train_data_.drop(['first'],axis=1)
train_data=train_data_.drop(['last'],axis=1)
train_data_.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,last,gender,street,city,state,zip,lat,long,city_pop,job,age,unix_time,merch_lat,merch_long,is_fraud,name
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",35,1325376018,36.011293,-82.048315,0,Jennifer Banks
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,45,1325376044,49.159047,-118.186462,0,Stephanie Gill
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,61,1325376051,43.150704,-112.154481,0,Edward Sanchez
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,1939,Patent attorney,56,1325376076,47.034331,-112.561071,0,Jeremy White
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Garcia,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,99,Dance movement psychotherapist,37,1325376186,38.674999,-78.632459,0,Tyler Garcia

In [19]:
train_data_=train_data_.drop(['street'],axis=1)
train_data_.sample(7)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,last,gender,city,state,zip,lat,long,city_pop,job,age,unix_time,merch_lat,merch_long,is_fraud,name
577193,577193,2019-09-01 19:42:06,375237305371366,fraud_Kutch-Wilderman,home,16.85,Erickson,M,East Rochester,NY,14445,43.1128,-77.4906,8019,Retail buyer,95,1346528526,43.590603,-78.279969,0,David Erickson
955588,955588,2020-01-19 05:08:32,4904681492230012,"fraud_Lind, Huel and McClure",gas_transport,55.81,Lowe,F,Cottekill,NY,12419,41.8467,-74.1038,722,Comptroller,33,1358572112,42.690631,-74.615776,0,Lisa Lowe
1270958,1270958,2020-06-12 03:09:00,213199865312311,fraud_Pfeffer and Sons,shopping_pos,61.26,Miller,M,Varnell,GA,30756,34.9298,-84.9885,74,Pensions consultant,79,1371006540,34.089526,-85.674846,0,Christopher Miller
749065,749065,2019-11-16 21:21:30,345060451158891,fraud_Nienow PLC,entertainment,54.29,Perez,M,Ashfield,MA,1330,42.5232,-72.8110,1506,"Production assistant, radio",63,1353100890,41.884533,-73.546351,0,Brian Perez
267461,267461,2019-05-12 18:28:11,372246459334925,"fraud_Hagenes, Kohler and Hoppe",food_dining,62.73,Martinez,M,Deadwood,SD,57732,44.3566,-103.6999,1979,Multimedia programmer,53,1336847291,45.085098,-103.176026,0,Rick Martinez
1203487,1203487,2020-05-18 07:52:22,377234009633447,fraud_Boyer PLC,shopping_net,5.17,Blackwell,F,Shenandoah Junction,WV,25442,39.3716,-77.8229,1925,Systems developer,57,1368863542,38.530053,-78.078590,0,Theresa Blackwell
225178,225178,2019-04-23 20:15:15,3567879740649740,fraud_Dietrich-Fadel,health_fitness,22.26,Williams,F,Brownville,NY,13615,44.0577,-76.0196,1271,"Producer, radio",65,1335212115,43.925926,-76.831873,0,Tanya Williams

In [20]:
train_data_['trans_date_trans_time'] = pd.to_datetime(train_data_['trans_date_trans_time'])
train_data_['trans_date_trans_time'].unique()

<DatetimeArray>
['2019-01-01 00:00:18', '2019-01-01 00:00:44', '2019-01-01 00:00:51',
 '2019-01-01 00:01:16', '2019-01-01 00:03:06', '2019-01-01 00:04:08',
 '2019-01-01 00:04:42', '2019-01-01 00:05:08', '2019-01-01 00:05:18',
 '2019-01-01 00:06:01',
 ...
 '2020-06-21 12:08:42', '2020-06-21 12:09:22', '2020-06-21 12:10:56',
 '2020-06-21 12:11:23', '2020-06-21 12:11:36', '2020-06-21 12:12:08',
 '2020-06-21 12:12:19', '2020-06-21 12:12:32', '2020-06-21 12:13:36',
 '2020-06-21 12:13:37']
Length: 1274791, dtype: datetime64[ns]

In [21]:
train_data_['year'] = train_data_['trans_date_trans_time'].dt.year
train_data_['month'] = train_data_['trans_date_trans_time'].dt.month
train_data_['day'] = train_data_['trans_date_trans_time'].dt.day
train_data_.drop('trans_date_trans_time', axis=1, inplace=True)
train_data_.sample(5)

,Unnamed: 0,cc_num,merchant,category,amt,last,gender,city,state,zip,lat,long,city_pop,job,age,unix_time,merch_lat,merch_long,is_fraud,name,year,month,day
490841,490841,3531129874770000,fraud_Little Ltd,kids_pets,93.17,Mitchell,F,Brandon,VT,5733,43.8065,-73.0882,5895,"Scientist, marine",48,1343938404,43.461934,-73.184308,0,Shelby Mitchell,2019,8,2
514153,514153,4026222041577,fraud_Wuckert-Goldner,home,12.99,Payne,F,Preston,CT,6365,41.5224,-71.9934,4720,Broadcast presenter,46,1344636721,41.845145,-71.391442,0,Debbie Payne,2019,8,10
1041401,1041401,4302480582202074,fraud_Kilback LLC,grocery_pos,62.83,Rodriguez,M,Muskegon,MI,49440,43.2326,-86.2492,128715,Historic buildings inspector/conservation officer,28,1362728485,43.850182,-85.925384,0,David Rodriguez,2020,3,8
691087,691087,4586260469584,fraud_Connelly-Carter,home,14.00,Thompson,F,Mound City,MO,64470,40.1362,-95.2138,1631,Architect,70,1350836541,40.486940,-95.872161,0,Melody Thompson,2019,10,21
280914,280914,4223708906367574214,fraud_O'Keefe-Hudson,grocery_pos,93.70,Riddle,M,Mount Saint Joseph,OH,45051,39.0965,-84.6431,177,Exhibition designer,49,1337386746,38.973647,-84.054145,0,Adam Riddle,2019,5,19

In [22]:
train_data_=train_data_.drop(columns=['last'])
#train_data_.head()

In [23]:
column_names = train_data_.columns
categorical_columns = [var for var in column_names if train_data_[var].dtype=='O']
print("The columns with categorical data are: {}".format(categorical_columns))

The columns with categorical data are: ['merchant', 'category', 'gender', 'city', 'state', 'job', 'name']

In [24]:
categorical_columns = categorical_columns[:-1]
categorical_columns

['merchant', 'category', 'gender', 'city', 'state', 'job']

In [27]:
train_data_['latitude difference'] =abs(train_data_['lat']-train_data_['merch_lat'])
train_data_['longitude difference'] =abs(train_data_['long']-train_data_['merch_long'])

In [28]:
train_data_['displacement'] = np.sqrt(pow((train_data_['latitude difference']*110),2) + pow((train_data_['longitude difference']*110),2))
train_data_.sample(5)

,Unnamed: 0,cc_num,merchant,category,amt,gender,city,state,zip,lat,long,city_pop,job,age,unix_time,merch_lat,merch_long,is_fraud,name,year,month,day,latitude difference,longitude difference,displacement
186331,186331,4104312520615374,fraud_Bogisich Inc,grocery_pos,137.84,F,Mountain Center,CA,92561,33.6401,-116.5567,1661,"Therapist, music",35,1333768035,32.668549,-117.488491,0,Brooke Rodriguez,2019,4,7,0.971551,0.931791,148.077562
1272435,1272435,375767678113375,"fraud_Moore, Williamson and Emmerich",home,54.80,M,Timberville,VA,22853,38.6476,-78.7717,4367,Waste management officer,61,1371062660,39.186277,-78.237461,0,Christopher Patterson,2020,6,12,0.538677,0.534239,83.453994
254587,254587,5559857416065248,fraud_Rolfson-Kunde,personal_care,47.53,M,Grenada,CA,96038,41.6125,-122.5258,589,Systems analyst,78,1336327135,42.473132,-122.167023,0,Jack Hill,2019,5,6,0.860632,0.358777,102.566278
1013093,1013093,343668971234893,"fraud_Moen, Reinger and Murphy",grocery_pos,130.46,F,Hopkins,SC,29061,33.9349,-80.8449,13717,Chiropodist,74,1361505890,33.662004,-81.597035,0,Sally Moore,2020,2,22,0.272896,0.752135,88.012325
1007549,1007549,4908846471916297,"fraud_Daugherty, Pouros and Beahan",shopping_pos,4.25,F,Grandview,TX,76050,32.2779,-97.2351,5875,"Radiographer, therapeutic",31,1361142988,31.913582,-96.661205,0,Lauren Torres,2020,2,17,0.364318,0.573895,74.774362

In [29]:
train_data_['displacement'] = round(train_data_['displacement'])
train_data_ = train_data_.drop(columns=['lat','long','merch_lat','merch_long','latitude difference','longitude difference'], axis=1)
train_data_.head()

,Unnamed: 0,cc_num,merchant,category,amt,gender,city,state,zip,city_pop,job,age,unix_time,is_fraud,name,year,month,day,displacement
0,0,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,Moravian Falls,NC,28654,3495,"Psychologist, counselling",35,1325376018,0,Jennifer Banks,2019,1,1,96.0
1,1,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,Orient,WA,99160,149,Special educational needs teacher,45,1325376044,0,Stephanie Gill,2019,1,1,30.0
2,2,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,M,Malad City,ID,83252,4154,Nature conservation officer,61,1325376051,0,Edward Sanchez,2019,1,1,107.0
3,3,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,Boulder,MT,59632,1939,Patent attorney,56,1325376076,0,Jeremy White,2019,1,1,101.0
4,4,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,M,Doe Hill,VA,24433,99,Dance movement psychotherapist,37,1325376186,0,Tyler Garcia,2019,1,1,96.0

In [30]:
train_data_ = train_data_.drop(['city','state','zip'], axis=1)
train_data_.head()

,Unnamed: 0,cc_num,merchant,category,amt,gender,city_pop,job,age,unix_time,is_fraud,name,year,month,day,displacement
0,0,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,3495,"Psychologist, counselling",35,1325376018,0,Jennifer Banks,2019,1,1,96.0
1,1,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,149,Special educational needs teacher,45,1325376044,0,Stephanie Gill,2019,1,1,30.0
2,2,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,M,4154,Nature conservation officer,61,1325376051,0,Edward Sanchez,2019,1,1,107.0
3,3,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,1939,Patent attorney,56,1325376076,0,Jeremy White,2019,1,1,101.0
4,4,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,M,99,Dance movement psychotherapist,37,1325376186,0,Tyler Garcia,2019,1,1,96.0

In [31]:
train_data_ = train_data_.drop(['Unnamed: 0'], axis=1)
train_data_.head()

,cc_num,merchant,category,amt,gender,city_pop,job,age,unix_time,is_fraud,name,year,month,day,displacement
0,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,3495,"Psychologist, counselling",35,1325376018,0,Jennifer Banks,2019,1,1,96.0
1,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,149,Special educational needs teacher,45,1325376044,0,Stephanie Gill,2019,1,1,30.0
2,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,M,4154,Nature conservation officer,61,1325376051,0,Edward Sanchez,2019,1,1,107.0
3,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,1939,Patent attorney,56,1325376076,0,Jeremy White,2019,1,1,101.0
4,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,M,99,Dance movement psychotherapist,37,1325376186,0,Tyler Garcia,2019,1,1,96.0

In [32]:
train_data_ = train_data_.drop(['name'], axis=1)
train_data_.head()

,cc_num,merchant,category,amt,gender,city_pop,job,age,unix_time,is_fraud,year,month,day,displacement
0,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,3495,"Psychologist, counselling",35,1325376018,0,2019,1,1,96.0
1,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,149,Special educational needs teacher,45,1325376044,0,2019,1,1,30.0
2,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,M,4154,Nature conservation officer,61,1325376051,0,2019,1,1,107.0
3,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,1939,Patent attorney,56,1325376076,0,2019,1,1,101.0
4,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,M,99,Dance movement psychotherapist,37,1325376186,0,2019,1,1,96.0

In [33]:
### Now, we can categorize the displacement column
train_data_['displacement'].unique()

array([ 96.,  30., 107., 101., 109., 130.,  13.,  33.,  74., 119.,  49.,
        78., 100.,  95.,  51.,  97.,  68.,  53., 122.,  26.,  94.,  84.,
        80.,  93.,  39.,  58.,  65.,  48.,  63.,  71.,  37.,  91.,  66.,
        99.,  77.,  36.,  87.,  56.,  34.,  24.,   9.,  88.,  57., 105.,
        15.,  69.,  59., 116., 126., 128.,  76., 102.,  81.,  46., 132.,
       112.,  90., 111., 103., 121.,  75., 108.,  82.,  52.,  98.,  70.,
       129., 124.,  43.,  62.,  92., 133., 106.,   5., 115.,  20.,  72.,
        27., 117.,  60.,  42., 139.,  16.,  10.,  79.,  47.,  44.,  40.,
       118., 113.,  86., 114., 110., 104., 149.,  67.,  89., 123.,  55.,
       143.,  73., 131.,  83.,  28., 136.,  85.,  38.,  54., 125., 135.,
        35.,  14.,  31.,  29., 138., 134., 147., 137.,  45.,  64.,  61.,
       152.,   8., 140.,  22., 141., 144., 146.,  12.,  18.,  25.,  23.,
        19., 120.,   7., 148.,  41., 145., 127.,   2., 153.,  21., 150.,
        50.,  32.,  11.,   3., 142., 151.,   0.,   6.,   4.,  17., 154.,
       155.,   1.])

In [34]:
train_data_['displacement'].describe()

count    1.296675e+06
mean     8.422295e+01
std      3.132332e+01
min      0.000000e+00
25%      6.200000e+01
50%      8.800000e+01
75%      1.080000e+02
max      1.550000e+02
Name: displacement, dtype: float64

In [35]:
train_data_.loc[(train_data_['displacement']<62),['proximity']] = "near"
train_data_.loc[((train_data_['displacement']>=62) &(train_data_['displacement']<108)), ['proximity']] = "far"
train_data_.loc[(train_data_['displacement']>=108), ['proximity']] = "very far"
train_data_.sample(10)

,cc_num,merchant,category,amt,gender,city_pop,job,age,unix_time,is_fraud,year,month,day,displacement,proximity
286912,571465035400,fraud_Tromp Group,travel,423.40,M,1645,Freight forwarder,47,1337553745,0,2019,5,20,86.0,far
379173,375082648741747,fraud_Durgan-Auer,misc_net,4.17,F,346,"Research officer, trade union",47,1340473702,0,2019,6,23,86.0,far
1139158,4908846471916297,fraud_Fahey Inc,kids_pets,37.61,F,5875,"Radiographer, therapeutic",31,1366410430,0,2020,4,19,28.0,near
188727,3506042666828517,fraud_Dietrich-Fadel,health_fitness,27.26,F,630,Fine artist,64,1333831572,0,2019,4,7,36.0,near
490580,4430881574719618,"fraud_Welch, Rath and Koepp",entertainment,59.40,F,61,Public relations account executive,84,1343930409,0,2019,8,2,62.0,far
1156287,3533742182628021,fraud_Dietrich-Fadel,health_fitness,173.07,M,20478,Materials engineer,26,1367064282,0,2020,4,27,106.0,far
946886,4792627764422477317,fraud_Jacobi and Sons,shopping_pos,409.48,F,5760,Chief Executive Officer,45,1358092889,0,2020,1,13,131.0,very far
26896,38580485618059,fraud_Harris Inc,gas_transport,65.72,F,248,Industrial/product designer,55,1326706073,0,2019,1,16,44.0,near
1260669,502012776709,fraud_Kilback Group,food_dining,32.03,F,165,Naval architect,78,1370697537,0,2020,6,8,130.0,very far
1013233,676173792455,"fraud_Kovacek, Dibbert and Ondricka",grocery_pos,67.91,F,92043,"Civil engineer, contracting",62,1361513040,0,2020,2,22,107.0,far

In [36]:
train_data_['city_pop'].describe()

count    1.296675e+06
mean     8.882444e+04
std      3.019564e+05
min      2.300000e+01
25%      7.430000e+02
50%      2.456000e+03
75%      2.032800e+04
max      2.906700e+06
Name: city_pop, dtype: float64

In [37]:
train_data_.loc[(train_data_['city_pop']<10000), ['city_population_status']] ="less dense"
train_data_.loc[((train_data_['city_pop']>1000) &(train_data_['city_pop']<50000)),['city_population_status']] = "normal"
train_data_.loc[(train_data_['city_pop']>50000),['city_population_status']] ="over crowded"
train_data_.sample(5)

,cc_num,merchant,category,amt,gender,city_pop,job,age,unix_time,is_fraud,year,month,day,displacement,proximity,city_population_status
981778,30197398657930,"fraud_Boehm, Predovic and Reinger",misc_pos,66.31,F,12335,Chief Strategy Officer,36,1359861669,0,2020,2,3,66.0,far,normal
1090936,3502088871723054,"fraud_Ruecker, Beer and Collier",shopping_net,5.15,M,19054,Operations geologist,47,1364589418,0,2020,3,29,91.0,far,normal
54924,501802953619,fraud_Botsford and Sons,home,11.59,M,308,Call centre manager,65,1328201980,0,2019,2,2,87.0,far,less dense
1171070,4658490815480264,"fraud_Stehr, Jewess and Schimmel",misc_net,79.35,F,184,Systems developer,78,1367634824,0,2020,5,4,111.0,very far,less dense
730168,4855488158131690372,fraud_Padberg-Rogahn,entertainment,62.88,M,970,Agricultural consultant,30,1352383045,0,2019,11,8,94.0,far,less dense

In [38]:
train_data_ = train_data_.drop(['city_pop'], axis=1)

In [39]:
train_data_.sample(20)

,cc_num,merchant,category,amt,gender,job,age,unix_time,is_fraud,year,month,day,displacement,proximity,city_population_status
1193804,4761403817546679245,fraud_Romaguera Ltd,health_fitness,24.83,F,Psychiatric nurse,37,1368455071,0,2020,5,13,43.0,near,normal
107163,370818583810103,fraud_Vandervort-Funk,grocery_pos,67.89,M,General practice doctor,47,1330742953,0,2019,3,3,93.0,far,normal
1083012,30029052116970,fraud_Erdman-Ebert,personal_care,5.67,M,Metallurgist,53,1364235898,0,2020,3,25,93.0,far,normal
871035,3575540972310993,fraud_Dare-Marvin,entertainment,54.62,F,Curator,22,1356010758,0,2019,12,20,73.0,far,normal
27711,4990494243023,fraud_Rempel Inc,shopping_net,199.13,M,Energy engineer,63,1326759737,0,2019,1,17,99.0,far,less dense
825144,4908846471916297,fraud_Hickle Group,shopping_pos,5.82,F,"Radiographer, therapeutic",31,1355065457,0,2019,12,9,114.0,very far,normal
442637,4450831335606294,fraud_Schiller Ltd,personal_care,5.37,F,Occupational psychologist,51,1342386966,0,2019,7,15,89.0,far,normal
1226118,3547574373318979,fraud_Morissette LLC,entertainment,15.84,M,"Psychologist, clinical",61,1369598159,0,2020,5,26,64.0,far,normal
1278257,6011252220172077,fraud_Wilkinson Ltd,entertainment,78.68,M,"Engineer, land",22,1371244903,0,2020,6,14,100.0,far,normal
619918,6569097840281287,"fraud_Schuppe, Nolan and Hoeger",shopping_pos,3.58,M,"Scientist, marine",54,1348192921,0,2019,9,21,56.0,near,over crowded
784968,4424338559877976,fraud_Kutch and Sons,grocery_pos,104.76,F,Private music teacher,66,1354340652,0,2019,12,1,129.0,very far,less dense
488874,4294040533480516,fraud_Jakubowski Inc,home,153.31,F,Biomedical scientist,37,1343864703,0,2019,8,1,99.0,far,normal
732912,3566094707272327,fraud_Reichel LLC,personal_care,44.57,F,Health physicist,52,1352479950,0,2019,11,9,138.0,very far,normal
920160,4642255475285942,"fraud_Romaguera, Wehner and Tromp",kids_pets,38.24,F,"Surveyor, minerals",36,1356890696,0,2019,12,30,60.0,near,less dense
164094,571844099986,"fraud_Baumbach, Strosin and Nicolas",shopping_pos,3.42,F,Engineering geologist,71,1332912999,0,2019,3,28,52.0,near,over crowded
826522,3560318482131952,fraud_Kutch-Wilderman,home,126.11,M,"Librarian, academic",68,1355081766,0,2019,12,9,11.0,near,normal
1109023,377026671291680,fraud_White and Sons,home,13.19,F,Investment analyst,49,1365257469,0,2020,4,6,23.0,near,less dense
543858,2720894374956739,"fraud_Hauck, Dietrich and Funk",kids_pets,90.07,F,"Psychologist, sport and exercise",96,1345501378,0,2019,8,20,80.0,far,normal
787309,30561214688470,fraud_Donnelly LLC,entertainment,119.23,F,"Scientist, research (maths)",25,1354376092,0,2019,12,1,121.0,very far,over crowded
186568,6011934240159560,fraud_Fisher-Schowalter,shopping_net,86.71,M,"Loss adjuster, chartered",49,1333776525,0,2019,4,7,72.0,far,less dense

In [40]:
train_data_['is_fraud'].value_counts()

is_fraud
0    1289169
1       7506
Name: count, dtype: int64

In [41]:
test_data_.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,NY,11710,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,Titusville,FL,32780,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,Falmouth,MI,49632,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [42]:
test_data_ = test_data_.drop(['trans_num'], axis=1)
test_data_.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,NY,11710,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,Titusville,FL,32780,28.5697,-80.8191,54767,Set designer,1987-07-25,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,Falmouth,MI,49632,44.2529,-85.0170,1126,Furniture designer,1955-07-06,1371816917,44.959148,-85.884734,0

In [44]:
def find_age(date_of_birth):
    year = int(date_of_birth[:4])
    return (2023 - year)
test_data_['dob'] = test_data_['dob'].apply(find_age)
test_data_.rename(columns={'dob':'age'}, inplace=True)
test_data_['age'].unique()

array([55, 33, 53, 36, 68, 32, 72, 51, 50, 67, 27, 47, 46, 86, 52, 35, 31,
       26, 38, 66, 75, 93, 49, 59, 65, 28, 43, 54, 48, 62, 80, 44, 37, 29,
       94, 89, 30, 24, 41, 25, 39, 45, 34, 56, 23, 74, 85, 57, 58, 78, 40,
       19, 71, 42, 73, 20, 69, 63, 82, 61, 77, 70, 99, 60, 22, 64, 97, 76,
       87, 88, 84, 81, 18, 79, 92, 96, 83, 95, 90, 91, 21], dtype=int64)

In [45]:
test_data_ = test_data_.drop(['first','last','city','street','zip'],axis=1)
test_data_.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,gender,state,lat,long,city_pop,job,age,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,M,SC,33.9659,-80.9355,333497,Mechanical engineer,55,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,F,UT,40.3207,-110.4360,302,"Sales professional, IT",33,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,F,NY,40.6729,-73.5365,34496,"Librarian, public",53,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,M,FL,28.5697,-80.8191,54767,Set designer,36,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,M,MI,44.2529,-85.0170,1126,Furniture designer,68,1371816917,44.959148,-85.884734,0

In [46]:
test_data_['trans_date_trans_time'] = pd.to_datetime(test_data_['trans_date_trans_time'])

In [47]:
test_data_['year'] = test_data_['trans_date_trans_time'].dt.year
test_data_['month'] = test_data_['trans_date_trans_time'].dt.month
test_data_['day'] = test_data_['trans_date_trans_time'].dt.day
test_data_.drop('trans_date_trans_time', axis=1, inplace=True)
test_data_.sample(5)

,Unnamed: 0,cc_num,merchant,category,amt,gender,state,lat,long,city_pop,job,age,unix_time,merch_lat,merch_long,is_fraud,year,month,day
267595,267595,30082025922891,"fraud_Reichert, Rowe and Mraz",shopping_net,5.51,F,FL,26.1184,-81.7361,276002,"Pilot, airline",89,1380365629,25.730443,-81.547666,0,2020,9,28
554870,554870,6011724471098086,fraud_Johns-Hoeger,entertainment,14.77,F,WA,46.1966,-118.9017,3684,Musician,42,1388516301,45.497685,-119.583515,0,2020,12,31
382199,382199,3587044315915002,fraud_Bradtke PLC,grocery_pos,99.65,M,TN,35.0659,-89.1534,1804,Clothing/textile technologist,49,1384673377,34.492804,-88.817087,0,2020,11,17
77397,77397,3527536963490470,fraud_Lesch Ltd,shopping_pos,1.03,F,SC,32.9413,-81.1807,1725,Social researcher,49,1374156462,33.393145,-81.395910,0,2020,7,18
417858,417858,3560697798177746,fraud_Huels-Hahn,gas_transport,65.21,M,CA,33.7163,-116.3381,4677,Learning mentor,68,1385886356,33.665963,-115.673526,0,2020,12,1

In [48]:
test_data_['latitude difference'] =abs(test_data_['lat']-test_data_['merch_lat'])
test_data_['longitude difference'] =abs(test_data_['long']-test_data_['merch_long'])

In [49]:
test_data_['displacement'] = np.sqrt(pow((test_data_['latitude difference']*110),2) + pow((test_data_['longitude difference']*110),2))
test_data_.sample(5)

,Unnamed: 0,cc_num,merchant,category,amt,gender,state,lat,long,city_pop,job,age,unix_time,merch_lat,merch_long,is_fraud,year,month,day,latitude difference,longitude difference,displacement
364553,364553,4587657402165341815,fraud_Beer-Jast,kids_pets,164.72,F,IL,41.0646,-87.5917,2135,"Psychotherapist, child",19,1384022174,40.423708,-87.577595,0,2020,11,9,0.640892,0.014105,70.515191
372944,372944,3560797065840735,fraud_Effertz LLC,entertainment,252.53,F,ND,46.1838,-101.2589,77,Film/video editor,34,1384357591,45.547922,-101.737034,0,2020,11,13,0.635878,0.478134,87.514174
508052,508052,375767678113375,"fraud_Becker, Harris and Harvey",personal_care,4.24,M,VA,38.6476,-78.7717,4367,Waste management officer,61,1387630563,39.334708,-78.758008,0,2020,12,21,0.687108,0.013692,75.596885
56329,56329,4998109455173950,fraud_Padberg-Rogahn,entertainment,93.59,F,MO,38.9621,-94.5959,545147,Counsellor,36,1373498105,39.177453,-94.091594,0,2020,7,10,0.215353,0.504306,60.319877
184892,184892,342952484382519,fraud_Bogisich-Homenick,misc_net,8.58,F,CT,42.0158,-73.2913,647,Comptroller,36,1377386678,42.179435,-72.581523,0,2020,8,24,0.163635,0.709777,80.123490

In [50]:
test_data_['displacement'] = round(test_data_['displacement'])
test_data_ = test_data_.drop(columns=['lat','long','merch_lat','merch_long','latitude difference','longitude difference'], axis=1)
test_data_.head()

,Unnamed: 0,cc_num,merchant,category,amt,gender,state,city_pop,job,age,unix_time,is_fraud,year,month,day,displacement
0,0,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,M,SC,333497,Mechanical engineer,55,1371816865,0,2020,6,21,29.0
1,1,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,F,UT,302,"Sales professional, IT",33,1371816873,0,2020,6,21,109.0
2,2,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,F,NY,34496,"Librarian, public",53,1371816893,0,2020,6,21,75.0
3,3,3591919803438423,fraud_Haley Group,misc_pos,60.05,M,FL,54767,Set designer,36,1371816915,0,2020,6,21,28.0
4,4,3526826139003047,fraud_Johnston-Casper,travel,3.19,M,MI,1126,Furniture designer,68,1371816917,0,2020,6,21,123.0

In [51]:
test_data_.loc[(test_data_['displacement']<62),['proximity']] = "near"
test_data_.loc[((test_data_['displacement']>=62) &(test_data_['displacement']<108)), ['proximity']] = "far"
test_data_.loc[(test_data_['displacement']>=108), ['proximity']] = "very far"
test_data_.sample(10)

,Unnamed: 0,cc_num,merchant,category,amt,gender,state,city_pop,job,age,unix_time,is_fraud,year,month,day,displacement,proximity
281126,281126,639046421587,fraud_Fahey Inc,kids_pets,52.63,M,PA,1140,"Administrator, education",37,1380896545,0,2020,10,4,125.0,very far
309206,309206,676173792455,fraud_Kessler Inc,travel,9.43,F,CA,92043,"Civil engineer, contracting",62,1381945610,0,2020,10,16,83.0,far
398700,398700,2714019737356678,fraud_Doyle Ltd,grocery_pos,53.68,F,PA,724,Theme park manager,28,1385302366,0,2020,11,24,69.0,far
174494,174494,4661996144291811856,fraud_Schmidt-Larkin,home,107.72,F,PA,2054,Operations geologist,60,1377102537,0,2020,8,21,68.0,far
16916,16916,4379260813815979609,"fraud_Rowe, Batz and Goodwin",grocery_pos,56.58,M,CA,381459,Barista,49,1372321494,0,2020,6,27,64.0,far
247999,247999,370877495212014,fraud_Murray Ltd,grocery_net,65.80,F,NC,21134,Dispensing optician,39,1379642021,0,2020,9,20,66.0,far
220858,220858,4220345354880,fraud_Lynch-Mohr,travel,1.06,M,MI,24840,Agricultural consultant,63,1378584460,0,2020,9,7,46.0,near
536586,536586,676298633337,"fraud_Nicolas, Hills and McGlynn",entertainment,10.64,F,WV,255,Chief Executive Officer,52,1388186410,0,2020,12,27,96.0,far
75377,75377,4935858973307492,fraud_Donnelly LLC,entertainment,75.13,M,GA,1841,Film/video editor,48,1374077897,0,2020,7,17,96.0,far
335779,335779,5580563567307107,fraud_Emmerich-Rau,personal_care,68.18,M,PA,1946,Charity fundraiser,33,1382899173,0,2020,10,27,36.0,near

In [52]:
train_data_ = train_data_.drop(['displacement'], axis=1)
test_data_ = test_data_.drop(['displacement'], axis=1)

In [54]:
test_data_.loc[(test_data_['city_pop']<10000), ['city_population_status']] ="less dense"
test_data_.loc[((test_data_['city_pop']>1000) &(test_data_['city_pop']<50000)),['city_population_status']] = "normal"
test_data_.loc[(test_data_['city_pop']>50000),['city_population_status']] ="over crowded"
test_data_.sample(5)

,Unnamed: 0,cc_num,merchant,category,amt,gender,state,city_pop,job,age,unix_time,is_fraud,year,month,day,proximity,city_population_status
365045,365045,3527536963490470,fraud_Nolan-Williamson,kids_pets,24.54,F,SC,1725,Social researcher,49,1384032457,0,2020,11,9,very far,normal
134373,134373,2264937662466770,fraud_Funk Group,grocery_net,9.55,M,TX,1595797,Land,28,1375876097,0,2020,8,7,very far,over crowded
136615,136615,675909898057,"fraud_Swaniawski, Lowe and Robel",shopping_pos,1.93,M,NY,7987,Television/film/video producer,59,1375956521,0,2020,8,8,far,normal
271866,271866,30357372465631,fraud_Schuppe LLC,entertainment,36.00,M,WI,1628,Civil Service fast streamer,56,1380479183,0,2020,9,29,very far,normal
429336,429336,4807552641361,fraud_Bradtke PLC,grocery_pos,154.52,F,OH,133,Professor Emeritus,69,1386135814,0,2020,12,4,near,less dense

In [55]:
test_data_ = test_data_.drop(['city_pop'], axis=1)

In [56]:
test_data_ = test_data_.drop(['state'], axis=1)
test_data_.sample(10)

,Unnamed: 0,cc_num,merchant,category,amt,gender,job,age,unix_time,is_fraud,year,month,day,proximity,city_population_status
286939,286939,6011581063717667,fraud_Reilly and Sons,health_fitness,45.68,M,Private music teacher,53,1381062380,0,2020,10,6,near,less dense
3724,3724,4311368326621416041,fraud_Goyette-Gerhold,kids_pets,89.31,M,Community arts worker,54,1371904813,0,2020,6,22,near,less dense
523961,523961,4173950183554608,fraud_Wuckert-Goldner,home,19.64,M,Health promotion specialist,45,1387927874,0,2020,12,24,far,normal
25138,25138,2254799658404120,fraud_Padberg-Sauer,home,80.03,F,Educational psychologist,36,1372532533,0,2020,6,29,very far,over crowded
377133,377133,4716561796955522,fraud_Pollich LLC,home,210.82,F,Water engineer,51,1384530921,0,2020,11,15,far,less dense
409957,409957,30270432095985,fraud_Pacocha-O'Reilly,grocery_pos,78.29,F,Environmental consultant,51,1385774932,0,2020,11,30,far,less dense
166092,166092,4981132848794,fraud_Kuhn LLC,misc_net,53.85,M,Child psychotherapist,77,1376811092,0,2020,8,18,very far,less dense
349190,349190,4653879239169997,fraud_Block-Parisian,misc_net,9.67,F,"Therapist, sports",24,1383432569,0,2020,11,2,far,normal
445140,445140,4727244663135968,fraud_Brown Inc,kids_pets,122.73,F,Science writer,94,1386429365,0,2020,12,7,near,normal
295722,295722,344709867813900,fraud_Corwin-Gorczany,misc_net,56.12,F,Environmental consultant,37,1381451560,0,2020,10,11,far,over crowded

In [57]:
train_data_.sample(10)

,cc_num,merchant,category,amt,gender,job,age,unix_time,is_fraud,year,month,day,proximity,city_population_status
234057,2713913904780408,fraud_DuBuque LLC,grocery_pos,110.74,F,Multimedia programmer,59,1335589196,0,2019,4,28,very far,normal
198637,4229733778084049,fraud_Haley Group,misc_pos,652.60,M,Surgeon,33,1334254818,0,2019,4,12,very far,normal
1242226,4451952084362894,"fraud_Brown, Homenick and Lesch",health_fitness,73.52,M,Petroleum engineer,43,1370117632,0,2020,6,1,near,less dense
804410,6593250708747804,fraud_Breitenberg-Hermiston,kids_pets,29.05,F,Paramedic,46,1354716209,0,2019,12,5,very far,normal
873776,341546199006537,fraud_Kilback LLC,grocery_pos,94.91,M,"Administrator, education",84,1356065874,0,2019,12,21,near,less dense
905081,6515067575568369,fraud_Marks Inc,gas_transport,75.64,M,Land/geomatics surveyor,33,1356674421,0,2019,12,28,very far,normal
426212,371284100299909,fraud_Mraz-Herzog,gas_transport,64.47,F,Early years teacher,47,1341917612,0,2019,7,10,far,less dense
615429,4810839835482794272,fraud_Shanahan-Lehner,personal_care,25.45,F,Production manager,38,1347988983,0,2019,9,18,near,less dense
437469,4259996134423,fraud_O'Connell-Ullrich,home,36.72,F,Probation officer,55,1342275795,0,2019,7,14,very far,less dense
1074328,4092452671396169678,"fraud_Armstrong, Walter and Gottlieb",food_dining,43.47,M,"Engineer, biomedical",78,1363965527,0,2020,3,22,very far,normal

In [59]:
temp_data = train_data_.drop(['job','merchant'], axis=1)
data_train_ = pd.get_dummies(temp_data, columns =['gender','proximity','city_population_status'], drop_first=True)
temp_data = test_data_.drop(['job','merchant'], axis=1)
data_test_ = pd.get_dummies(temp_data, columns =['gender','proximity','city_population_status'], drop_first=True)
data_test_.head()

,Unnamed: 0,cc_num,category,amt,age,unix_time,is_fraud,year,month,day,gender_M,proximity_near,proximity_very far,city_population_status_normal,city_population_status_over crowded
0,0,2291163933867244,personal_care,2.86,55,1371816865,0,2020,6,21,True,True,False,False,True
1,1,3573030041201292,personal_care,29.84,33,1371816873,0,2020,6,21,False,False,True,False,False
2,2,3598215285024754,health_fitness,41.28,53,1371816893,0,2020,6,21,False,False,False,True,False
3,3,3591919803438423,misc_pos,60.05,36,1371816915,0,2020,6,21,True,True,False,False,True
4,4,3526826139003047,travel,3.19,68,1371816917,0,2020,6,21,True,False,True,True,False

In [60]:
data_train_.head()

,cc_num,category,amt,age,unix_time,is_fraud,year,month,day,gender_M,proximity_near,proximity_very far,city_population_status_normal,city_population_status_over crowded
0,2703186189652095,misc_net,4.97,35,1325376018,0,2019,1,1,False,False,False,True,False
1,630423337322,grocery_pos,107.23,45,1325376044,0,2019,1,1,False,True,False,False,False
2,38859492057661,entertainment,220.11,61,1325376051,0,2019,1,1,True,False,False,True,False
3,3534093764340240,gas_transport,45.00,56,1325376076,0,2019,1,1,True,False,False,True,False
4,375534208663984,misc_pos,41.96,37,1325376186,0,2019,1,1,True,False,False,False,False

In [61]:
data_train_ = pd.get_dummies(data_train_, columns = ['category'], drop_first =True)
data_test_ = pd.get_dummies(data_test_, columns = ['category'], drop_first =True)
data_train_.head()

,cc_num,amt,age,unix_time,is_fraud,year,month,day,gender_M,proximity_near,proximity_very far,city_population_status_normal,city_population_status_over crowded,category_food_dining,category_gas_transport,category_grocery_net,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel
0,2703186189652095,4.97,35,1325376018,0,2019,1,1,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1,630423337322,107.23,45,1325376044,0,2019,1,1,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,38859492057661,220.11,61,1325376051,0,2019,1,1,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,3534093764340240,45.00,56,1325376076,0,2019,1,1,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False
4,375534208663984,41.96,37,1325376186,0,2019,1,1,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False

In [62]:
X = data_train_.drop(['is_fraud'], axis=1)
y = data_train_['is_fraud']
X_test = data_test_.drop(['is_fraud','Unnamed: 0'], axis=1)
y_test = data_test_['is_fraud']

In [63]:
scaler = MinMaxScaler()

In [64]:
data_train_ = scaler.fit_transform(data_train_)
data_test_ = scaler.fit_transform(data_test_)

In [74]:
#model training
#logistic regression
logreg = LogisticRegression(solver='liblinear', random_state=0)
logreg.fit(X,y)

LogisticRegression(random_state=0, solver='liblinear')

In [66]:
y_pred_test = logreg.predict(X_test)
y_pred_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [67]:
X_test

,cc_num,amt,age,unix_time,year,month,day,gender_M,proximity_near,proximity_very far,city_population_status_normal,city_population_status_over crowded,category_food_dining,category_gas_transport,category_grocery_net,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel
0,2291163933867244,2.86,55,1371816865,2020,6,21,True,True,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False
1,3573030041201292,29.84,33,1371816873,2020,6,21,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
2,3598215285024754,41.28,53,1371816893,2020,6,21,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,3591919803438423,60.05,36,1371816915,2020,6,21,True,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False
4,3526826139003047,3.19,68,1371816917,2020,6,21,True,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,30560609640617,43.77,57,1388534347,2020,12,31,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
555715,3556613125071656,111.84,24,1388534349,2020,12,31,True,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
555716,6011724471098086,86.88,42,1388534355,2020,12,31,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
555717,4079773899158,7.99,58,1388534364,2020,12,31,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
555718,4170689372027579,38.13,30,1388534374,2020,12,31,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False

In [68]:
#checking accuracy scores
print('The accuracy score is: {0:0.4f}'.format(accuracy_score(y_test,y_pred_test)))

The accuracy score is: 0.9961

In [69]:
#99.61% is great accuracy, which means our model is performing wonderful!!
#Confusion Matrix
cm = confusion_matrix(y_test,y_pred_test)
cm

array([[553574,      0],
       [  2145,      0]], dtype=int64)

In [70]:
cr = classification_report(y_test,y_pred_test)
print(cr)

C:\ProgramFiles\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramFiles\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.00      0.00      0.00      2145

    accuracy                           1.00    555719
   macro avg       0.50      0.50      0.50    555719
weighted avg       0.99      1.00      0.99    555719

C:\ProgramFiles\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [75]:
#random forest
randf = RandomForestClassifier(n_estimators=10,random_state=0)
randf.fit(X,y)

RandomForestClassifier(n_estimators=10, random_state=0)

In [72]:
y_pred_randf = randf.predict(X_test)

In [73]:
print('The accuracy score is: {0:0.4f}'.format(accuracy_score(y_test,y_pred_randf)))

The accuracy score is: 0.9976